# IPL Winning Predictor

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv("dataset_ipl.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71342 entries, 0 to 71341
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   batting_team  71342 non-null  object
 1   bowling_team  71342 non-null  object
 2   city          71342 non-null  object
 3   runs_left     71342 non-null  int64
 4   balls_left    71342 non-null  int64
 5   wickets       71342 non-null  int64
 6   total_runs_x  71342 non-null  int64
 7   crr           71342 non-null  float64
 8   rrr           71342 non-null  float64
 9   result        71342 non-null  int64
dtypes: float64(2), int64(5), object(3)
memory usage: 5.4+ MB

In [4]:
df.describe()

,runs_left,balls_left,wickets,total_runs_x,crr,rrr,result
count,71342.000000,71342.000000,71342.000000,71342.000000,71342.000000,71342.000000,71342.000000
mean,92.621065,62.878725,7.553251,165.726963,7.447791,10.368308,0.526646
std,49.957572,33.259471,2.124334,29.294967,2.280498,13.726365,0.499293
min,-16.000000,-2.000000,0.000000,65.000000,0.000000,-510.000000,0.000000
25%,53.000000,35.000000,6.000000,147.000000,6.265782,7.151515,0.000000
50%,92.000000,64.000000,8.000000,165.000000,7.500000,8.880000,1.000000
75%,130.000000,92.000000,9.000000,185.000000,8.696385,10.894737,1.000000
max,249.000000,119.000000,10.000000,250.000000,42.000000,678.000000,1.000000

In [5]:
df.head()

,batting_team,bowling_team,city,runs_left,balls_left,wickets,total_runs_x,crr,rrr,result
0,Royal Challengers Bangalore,Delhi Daredevils,Delhi,121,67,7,191,7.924528,10.835821,0
1,Rajasthan Royals,Chennai Super Kings,Jaipur,106,72,7,141,4.375000,8.833333,1
2,Delhi Daredevils,Rajasthan Royals,Delhi,16,12,7,165,8.277778,8.000000,0
3,Rajasthan Royals,Mumbai Indians,Jaipur,104,62,8,172,7.034483,10.064516,1
4,Sunrisers Hyderabad,Delhi Capitals,Delhi,23,37,7,134,8.024096,3.729730,1

In [6]:
df['batting_team'].unique()

array(['Royal Challengers Bangalore', 'Rajasthan Royals',
       'Delhi Daredevils', 'Sunrisers Hyderabad', 'Chennai Super Kings',
       'Mumbai Indians', 'Kings XI Punjab', 'Kolkata Knight Riders',
       'Deccan Chargers', 'Delhi Capitals'], dtype=object)

In [7]:
df['batting_team'] = df['batting_team'].str.replace('Delhi Daredevils','Delhi Capitals')
df['bowling_team'] = df['bowling_team'].str.replace('Delhi Daredevils','Delhi Capitals')

df['batting_team'] = df['batting_team'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
df['bowling_team'] = df['bowling_team'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

In [8]:
df['batting_team'].unique()

array(['Royal Challengers Bangalore', 'Rajasthan Royals',
       'Delhi Capitals', 'Sunrisers Hyderabad', 'Chennai Super Kings',
       'Mumbai Indians', 'Kings XI Punjab', 'Kolkata Knight Riders'],
      dtype=object)

In [9]:
df.columns

Index(['batting_team', 'bowling_team', 'city', 'runs_left', 'balls_left',
       'wickets', 'total_runs_x', 'crr', 'rrr', 'result'],
      dtype='object')

In [10]:
X = df[['batting_team','bowling_team','city',
        'runs_left','balls_left','wickets',
        'total_runs_x','crr','rrr']]

y = df['result']

In [11]:
X = pd.get_dummies(X)
model_columns = X.columns

In [12]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [14]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [15]:
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test,y_pred))

Accuracy: 0.801457705515453

In [16]:
teams = sorted(df['batting_team'].unique())
cities = sorted(df['city'].unique())

print("Teams:\n")
for t in teams:
    print(t)

print("\nCities:\n")
for c in cities:
    print(c)

Teams:

Chennai Super Kings
Delhi Capitals
Kings XI Punjab
Kolkata Knight Riders
Mumbai Indians
Rajasthan Royals
Royal Challengers Bangalore
Sunrisers Hyderabad

Cities:

Abu Dhabi
Ahmedabad
Bangalore
Bengaluru
Bloemfontein
Cape Town
Centurion
Chandigarh
Chennai
Cuttack
Delhi
Dharamsala
Durban
East London
Hyderabad
Indore
Jaipur
Johannesburg
Kimberley
Kolkata
Mohali
Mumbai
Nagpur
Port Elizabeth
Pune
Raipur
Ranchi
Sharjah
Visakhapatnam

In [32]:
print("\nEnter Second Innings Match Details:\n")

batting_team = input("Batting Team: ")
bowling_team = input("Bowling Team: ")
city = input("City: ")

target = int(input("Target (1st innings score): "))
score = int(input("Current Score (2nd innings): "))
overs_completed = float(input("Overs Completed: "))
wickets_out = int(input("Wickets Out: "))

Enter Second Innings Match Details:

Batting Team:  Sunrisers Hyderabad
Bowling Team:  Mumbai Indians
City:  Mumbai
Target (1st innings score):  244
Current Score (2nd innings):  100
Overs Completed:  6
Wickets Out:  0

In [33]:
# Convert overs into balls
overs_int = int(overs_completed)
balls_part = int((overs_completed - overs_int) * 10)

balls_bowled = overs_int * 6 + balls_part
balls_left = 120 - balls_bowled

runs_left = target - score
wickets = 10 - wickets_out
total_runs_x = target

crr = score / (balls_bowled / 6)
rrr = (runs_left * 6) / balls_left

In [34]:
input_df = pd.DataFrame([{
    'batting_team': batting_team,
    'bowling_team': bowling_team,
    'city': city,
    'runs_left': runs_left,
    'balls_left': balls_left,
    'wickets': wickets,
    'total_runs_x': target,
    'crr': crr,
    'rrr': rrr
}])

In [35]:
input_df = pd.get_dummies(input_df)

for col in model_columns:
    if col not in input_df.columns:
        input_df[col] = 0

input_df = input_df[model_columns]
input_df = scaler.transform(input_df)

In [36]:
prob = model.predict_proba(input_df)

batting_prob = prob[0][1] * 100
bowling_prob = prob[0][0] * 100

print("\n🏏 Win Probability:\n")
print(f"{batting_team} : {batting_prob:.2f}%")
print(f"{bowling_team} : {bowling_prob:.2f}%")

🏏 Win Probability:

Sunrisers Hyderabad : 23.05%
Mumbai Indians : 76.95%

In [25]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [26]:
import pickle
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse_output=False,drop='first'),['batting_team','bowling_team','city'])
]
,remainder='passthrough')
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [27]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [28]:
pred = pipe.predict(X_test)

In [29]:
accuracy_score(y_test,pred)

0.7992851636414605

In [30]:
pipe.predict_proba(X_test)[10]

array([0.91699712, 0.08300288])

In [ ]:
pickle.dump(pipe,open('pipeipl.pkl','wb'))